services:
  identity-db:
    build:
      context: .
      dockerfile: docker/postgresql/Dockerfile
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
