services:
  identity-db:
    image: postgis/postgis:16-3.4
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
