services:
  # api:
  #   build:
  #     context: .
  #     dockerfile: docker/api/Dockerfile
  #   ports:
  #     - ${BEAT_IDENTITY_SERVER}:${BEAT_IDENTITY_SERVER}
  #   env_file:
  #     - .env
  #   networks:
  #     - dev-net
  #   depends_on:
  #     identity-db:
  #       condition: service_healthy
  #     redis:
  #       condition: service_started
  #     broker:
  #       condition: service_healthy

  redis:
    container_name: redis
    image: docker.io/redis/redis-stack:latest
    ports:
      - "${REDIS_PORT}:6379"
      - "${REDIS_UI_PORT}:8001"
