@token = eyJhbGciOiJSUzI1NiIsImtpZCI6IjFkOGIxOWJlY2Y1ZmFjODJlZDY5Y2E2NTgwMTc3MWI2MDQ5YTgxODgxYjc2YzZmNzMyMDE4NDlkNTMyZTE3MDAiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJCZWF0Iiwic3ViIjoiMDNhZTJjZWUtNjY0NS00N2Y3LThjYWUtMzBiNjE1ZWZiYjU4IiwiYXVkIjpbIkJlYXQiXSwiZXhwIjoxNzM3MjE3NDQ2LCJpYXQiOjE3MzcyMTY4NDYsImp0aSI6IjIyMTg2MGMwLWJiZjgtNDBmOC1iYmQ3LWM4MzYyMDI5MDllMSIsImVtYWlsIjoiZGlvZ29hc3N1bmNhb0BpcHZjLnB0Iiwicm9sZSI6ImNsaWVudCIsInByb2ZpbGVJZCI6IjM3YTYwYTk2LTk5ZGYtNGQ0Zi05ODliLTAwODE3ZGUyNGIzMyIsInByb2ZpbGVJZHMiOlsiNjlmNjMwMzYtZDYwOC00NTRlLTlmYWItYjI4YzY4NjVhZGRjIl19.eNhIGdsyHh1Vc9LWnAm7Ro-K1tbcxZKGqUvE70texr9JGCh_-9XL_MSUeTRkhB6a3VYxy8lH0bwYBenL0KRA9-JRntXZEkjLeLr3_TXvWDShAJLsjGz7V8JPSIEdoK5ooN6RleA2VlmoecXGwMTHJksgxz7lqI6UY3tmb2md9hBxdC7TvcVRJBpnxVxUBFQTCMZSarz0cupO7nbpRKSC6rI2fqqShbaaf-FPPRwhG49de_OUlDqtD8t7mVl7mbPzPzKJld65QuBbobf5eUwMRDrWu0bHcrGpwOnyCH94EKj4v3qpCZjNnhuRd3Rj-ULTeCYR7lGrbTetkLaelxARDw

@profile_id = 37a60a96-99df-4d4f-989b-00817de24b33

GET /auth/refresh-token?profile_id={{profile_id}} HTTP/1.1
Host: {{BASE_URL}}
Content-Type: application/json
Authorization: Bearer {{token}}
