@token = eyJhbGciOiJSUzI1NiIsImtpZCI6IjFkOGIxOWJlY2Y1ZmFjODJlZDY5Y2E2NTgwMTc3MWI2MDQ5YTgxODgxYjc2YzZmNzMyMDE4NDlkNTMyZTE3MDAiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJCZWF0Iiwic3ViIjoiMDNhZTJjZWUtNjY0NS00N2Y3LThjYWUtMzBiNjE1ZWZiYjU4IiwiYXVkIjpbIkJlYXQiXSwiZXhwIjoxNzM3MjA1MTA0LCJpYXQiOjE3MzcyMDQ1MDQsImp0aSI6IjFjZTNlMzBmLWU3OGQtNDdmNy1hM2YzLTNiOThiZjYxODY0NyIsImVtYWlsIjoiZGlvZ29hc3N1bmNhb0BpcHZjLnB0Iiwicm9sZSI6ImNsaWVudCIsInByb2ZpbGVJZCI6IjY5ZjYzMDM2LWQ2MDgtNDU0ZS05ZmFiLWIyOGM2ODY1YWRkYyIsInByb2ZpbGVJZHMiOltdfQ.Em1qRbEweGRSPHcIK6L2JesJB1a4GlHzFNOyumnxTYk9s97e3h1IK8qcPRn_uY5XonuT4u6uRaP45JJLdXBXLwKUii0nQzsGeqiKN9Q5Ac4qDCO_wfGM_IO8WIxP0Rm8TBjF2ZnneF7sJ5YFp-sq_8jOPcTIvPu9J755LI2NVGm5Jqt-YYxFGe2NRaZtw8doRMlsW-KYgLcJWjiJjpyg5JGZqEoCTqW3LSj75eiFovcPDtWtUDPjZjF1KAImhh98BO2YaYWke9SsYP50JPeBR5mw57GXWa_1G73rM4S4Rj-DtWOJGhFkmeDDZCJMaWKdIAfHsXeDAK4unx9Q5mV9QQ

POST /auth/profile HTTP/1.1
Host: {{BASE_URL}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "grant_type": 0
}
